#!/usr/bin/env python3
"""
Manim Presentation Script: FIFA World Cup 2026 GNN + BNN Prediction Model
High-Fidelity 3Blue1Brown-Style Documentary Video
"""

import os
import sys
import subprocess
import shutil
import zipfile
import numpy as np
import time

# ──────────────────────────────────────────────
# 1. KAGGLE LATEX AUTOCONFIG
# ──────────────────────────────────────────────
if __name__ == "__main__" and os.path.basename(sys.argv[0]) in ["manim_presentation.py", "manim_presentationn.py"]:
    if not shutil.which("latex"):
        print("LaTeX not found. Installing system dependencies for Manim...")
        try:
            cmd_prefix = ["sudo"] if shutil.which("sudo") else []
            subprocess.run(cmd_prefix + ["apt-get", "update"], check=True)
            subprocess.run(cmd_prefix + ["apt-get", "install", "-y", "texlive", "texlive-latex-extra", "texlive-fonts-recommended", "dvipng", "dvisvgm"], check=True)
            print("LaTeX and system dependencies installed successfully!")
        except Exception as e:
            print(f"Error installing LaTeX: {e}")

from manim import *

config.background_color = "#060b08"  # Dark pitch-green background

# ──────────────────────────────────────────────
# Helper: Find Image Paths
# ──────────────────────────────────────────────
def get_image_path(filename):
    """Smart path resolver for Kaggle and Local environments."""
    possible_paths = [
        os.path.join("outputs", filename),
        os.path.join("..", "outputs", filename),
        os.path.join(".", filename),
        os.path.join("..", filename)
    ]
    for path in possible_paths:
        if os.path.exists(path):
            return path
    return None

# ──────────────────────────────────────────────
# MAIN DOCUMENTARY SCENE
# ──────────────────────────────────────────────
class WorldCupDocumentary(MovingCameraScene):
    def construct(self):
        # Setup Subtitles Engine
        self.subtitle_bg = Rectangle(width=14, height=1.5, color=BLACK, fill_opacity=0.7).to_edge(DOWN, buff=0)
        self.subtitle_bg.set_z_index(100)
        self.current_subtitle = None
        self.add(self.subtitle_bg)
        
        def speak(text, duration_mult=0.15):
            """Displays subtitle and waits based on length."""
            if self.current_subtitle:
                self.remove(self.current_subtitle)
            
            sub = Text(text, font_size=20, color=WHITE).move_to(self.subtitle_bg.get_center())
            sub.set_z_index(101)
            self.current_subtitle = sub
            
            self.play(Write(sub, run_time=min(1.5, len(text)*0.03)))
            self.wait(len(text.split()) * duration_mult)
        
        # ── SCENE 1: INTRODUCTION & THE BRACKET ──
        speak("Predicting the FIFA World Cup is inherently chaotic.")
        
        title = Tex(r"FIFA World Cup 2026\\Prediction Model", font_size=60, color=GOLD)
        self.play(FadeIn(title, shift=UP))
        speak("Upsets happen. Favorites fall. And traditional models fail because they can't handle uncertainty.")
        
        self.play(title.animate.to_edge(UP).scale(0.6))
        
        funnel_path = get_image_path("02_tournament_funnel.png")
        if funnel_path:
            funnel_img = ImageMobject(funnel_path).scale(0.6).shift(DOWN * 0.5)
            self.play(FadeIn(funnel_img))
            speak("Here is the tournament funnel generated by our model. A brutal path to the final.")
            
            # Camera zoom to the end of the funnel
            self.play(self.camera.frame.animate.scale(0.6).move_to(funnel_img.get_right() + LEFT*2), run_time=3)
            speak("But how did we get these numbers? How does a machine learn the flow of international football?")
            
            # Reset camera and clear
            self.play(self.camera.frame.animate.scale(1/0.6).move_to(ORIGIN))
            self.play(FadeOut(funnel_img))
        else:
            speak("Our model generates a complex tournament bracket, mapping the brutal path to the final.")
            speak("But how did we arrive at these numbers? Let's look at the math.")
        
        self.play(FadeOut(title))

        # ── SCENE 2: MATHEMATICAL FOUNDATION ──
        math_title = Tex("Mathematical Foundation", color=BLUE).to_edge(UP)
        self.play(Write(math_title))
        
        speak("We start with the baseline: The Elo Rating System.")
        
        elo_eq = MathTex(
            "E_A", "=", r"\frac{1}{1 + 10^{(R_B - R_A) / 400}}"
        )
        self.play(Write(elo_eq))
        speak("This elegant formula gives us the expected win probability of Team A over Team B based on their ratings.")
        
        # Transform Elo to Form
        speak("But Elo alone is too rigid. It ignores momentum. We must factor in historical form.")
        
        form_eq = MathTex(
            r"\text{Form}_A(t)", "=", r"\sum_{i}", "w_i", "(S_i - E_i)", r"e^{-\lambda (t - t_i)}"
        )
        self.play(TransformMatchingTex(elo_eq, form_eq, key_map={"E_A": "(S_i - E_i)"}))
        
        decay_box = SurroundingRectangle(form_eq[-1], color=ORANGE, buff=0.1)
        self.play(Create(decay_box))
        speak("This exponential decay component ensures that recent matches hold far more weight than matches from years ago.")
        self.play(FadeOut(decay_box), FadeOut(form_eq), FadeOut(math_title))

        # ── SCENE 3: GRAPH NEURAL NETWORKS ──
        gnn_title = Tex("Graph Neural Networks", color=GREEN).to_edge(UP)
        self.play(Write(gnn_title))
        
        speak("However, international teams don't exist in a vacuum. They form a complex web of interactions.")
        
        arch_path = get_image_path("09_model_architecture.png")
        if arch_path:
            arch_img = ImageMobject(arch_path).scale(0.5).shift(DOWN * 0.5)
            self.play(FadeIn(arch_img))
            speak("We model this as a Graph. Nodes are teams, and edges are historical matches.")
            speak("Our Graph Convolutional Network allows information to flow. A team gains implicitly by playing a tough opponent.")
            
            # Pan across the architecture diagram
            self.play(self.camera.frame.animate.scale(0.7).move_to(arch_img.get_left()), run_time=2)
            self.wait(1)
            self.play(self.camera.frame.animate.move_to(arch_img.get_right()), run_time=3)
            self.play(self.camera.frame.animate.scale(1/0.7).move_to(ORIGIN))
            self.play(FadeOut(arch_img))
        else:
            speak("We model the football world as a Graph. Nodes are teams, and edges are historical matches.")
            speak("Our GCN architecture allows hidden dynamics to propagate through the network.")
        
        self.play(FadeOut(gnn_title))

        # ── SCENE 4: BAYESIAN UNCERTAINTY ──
        bnn_title = Tex("Bayesian Neural Networks", color=YELLOW).to_edge(UP)
        self.play(Write(bnn_title))
        
        speak("A traditional neural network gives a single deterministic answer. In football, that's dangerous.")
        
        axes = Axes(x_range=[-3, 3, 1], y_range=[0, 1.2, 0.2], x_length=6, y_length=3).shift(DOWN * 0.5)
        self.play(Create(axes))
        
        vl = Line(axes.c2p(0, 0), axes.c2p(0, 1.0), color=RED, stroke_width=4)
        self.play(Create(vl))
        speak("Instead of a single fixed weight...")
        
        gaussian_graph = axes.plot(lambda x: np.exp(-0.5 * (x/0.8)**2), color=YELLOW)
        self.play(ReplacementTransform(vl, gaussian_graph))
        speak("Our Bayesian Neural Network outputs a probability distribution for every parameter.")
        speak("This allows the model to say 'I don't know' when a match is highly volatile.")
        
        self.play(FadeOut(axes), FadeOut(gaussian_graph), FadeOut(bnn_title))

        # ── SCENE 5: RESULTS & PREDICTIONS ──
        res_title = Tex("Monte Carlo Simulations", color=ORANGE).to_edge(UP)
        self.play(Write(res_title))
        
        speak("With our Bayesian uncertainty captured, we simulate the entire tournament 10,000 times.")
        
        prob_path = get_image_path("01_top20_win_probability.png")
        if prob_path:
            prob_img = ImageMobject(prob_path).scale(0.55).shift(DOWN * 0.5)
            self.play(FadeIn(prob_img))
            speak("The result converges into our Top 20 Win Probability chart.")
            speak("Notice the top contenders. The tight margins represent the true chaos of the knockout stages.")
            
            # Zoom to the top contenders (left side of the bar chart usually)
            self.play(self.camera.frame.animate.scale(0.6).move_to(prob_img.get_top() + DOWN), run_time=3)
            self.wait(1)
            self.play(self.camera.frame.animate.scale(1/0.6).move_to(ORIGIN))
            self.play(FadeOut(prob_img))
        else:
            speak("The results converge to reveal the true titans of the tournament, factoring in the chaos of knockout stages.")

        speak("And that is how we combine mathematical modeling, graph theory, and bayesian statistics...")
        
        final_text = Tex("To predict the World Cup.", color=GOLD, font_size=50)
        self.play(FadeOut(res_title), FadeOut(self.subtitle_bg), FadeOut(self.current_subtitle))
        self.play(Write(final_text))
        self.wait(3)
        self.play(FadeOut(final_text))


# ──────────────────────────────────────────────
# AUTOMATIC RUNNER (FOR KAGGLE SINGLE-FILE RUN)
# ──────────────────────────────────────────────
if __name__ == "__main__" and os.path.basename(sys.argv[0]) in ["manim_presentation.py", "manim_presentationn.py"]:
    print("\n🎬 Starting Manim Render...")
    script_name = os.path.basename(sys.argv[0])
    
    # We use -pqh if we want high quality, or -ql for testing. 
    # Since it's a documentary, we run standard quality (720p 30fps) to balance speed and look.
    render_cmd = f"manim -qm {script_name} -a"
    print(f"Running command: {render_cmd}")
    os.system(render_cmd)
    
    print("\n📦 Zipping output videos...")
    zip_path = "manim_videos.zip"
    if os.path.exists("media"):
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files in os.walk("media"):
                for file in files:
                    file_path = os.path.join(root, file)
                    arcname = os.path.relpath(file_path, start=".")
                    zipf.write(file_path, arcname=arcname)
        print(f"✅ Created zip archive: {zip_path}")
    else:
        print("❌ Error: 'media' directory not found. Rendering might have failed.")
